### ISSUE TITLE
Float parsing

### ISSUE THREAD

**Issue by piotrrzysko** [simdjson/simdjson-java#5]
Currently, float parsing is only partially supported. To see which cases are handled and which are not, run `org.simdjson.SimdJsonParserTest#testFloatValues`. We would like to cover all cases described in [the JSON specification](https://datatracker.ietf.org/doc/html/rfc8259#section-6).

**Comment by JohannesLichtenberger** [comment]
I'd have some time currently, because I have holidays and switching the job afterwards (maybe doing embedded stuff in the future, which would be completely new ;-)).

That said, I'm currently writing a technical design document about SirixDB: https://sirix.io/docs/concepts.html 

So it's not urgent :-) and there's plenty of other stuff to do regarding SirixDB 🙄
