### ISSUE TITLE
UTF-8 validation

### ISSUE THREAD

**Issue by piotrrzysko** [simdjson/simdjson-java#6]
The C++ version of simdjson [validates character encoding](https://github.com/simdjson/simdjson/blob/master/src/generic/stage1/utf8_validator.h#L19). We would like to have such validation in simdjson-java as well.

Perhaps, as @amCap1712 [suggested](https://github.com/simdjson/simdjson/issues/121#issuecomment-1638470097), we may utilize the great work done by @AugustNagro: https://github.com/AugustNagro/utf8.java

**Comment by AugustNagro** [comment]
Nice work Piotr!

Please feel free to use or copy the utf8 validation code as you wish.

While the code is correct you may find new optimization opportunities. The
vector api has certainly improved since java 17. I personally have been
waiting for the API to graduate from 'incubator' to 'preview' to give the
library an overhaul. It's also my (perhaps outdated) understanding that the
vector api will only ship after valhalla value types.

There was an effort here to improve the library with loop unrolling, etc:
https://github.com/merykitty/utf8-validator/tree/master

**Comment by piotrrzysko** [comment]
Implemented in https://github.com/simdjson/simdjson-java/pull/13.
